swagger: '2.0'

info:
  version: "1.0.0"
  title: Backend for storefront

paths:
  /products:
    get:
      description: |
         Get an index of all products

      parameters:
        -
          name: category
          in: path
          description: Id of array
          required: true
          type: number
          format: double

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string