version: '3.9'

services:
    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'
        env_file:
            - .env
        volumes:
            - 'postgres:/var/lib/postgresql/data'
        networks:
            - backend
        hostname: postgres
        restart: always
        user: root

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - 3001:80
        volumes:
            - pgadmin:/var/lib/pgadmin4/storage
        env_file:
            - .env
        depends_on:
            - postgres
        restart: always
        networks:
            - backend
            - frontend


    api:
        build: ./backend
        container_name: backend
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - postgres
        networks:
            - backend
            - frontend

volumes:
  postgres:
  pgadmin:

networks:
    frontend:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
    backend:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.20.0/24
# docker network create --subnet 192.168.20.0/24 backend-driver