version: '3.9'

services:
    postgres:
        image: postgres: latest
        ports:
            - '5432:5432'
    env_file:
        - .env
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
        - 'postgres:/var/lib/postgresql/data'
    networks:
        - backend
    hostname: postgres
    restart: always
    user: root

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - 3001:80
        volumes:
            - ./pgadmin:/var/lib/pgadmin/storage
        environment:
            PGADMIN_DEFAULT_EMAIL: root
            PGADMIN_DEFAULT_PASSWORD: root
        depends_on:
            - postgres
        restart: always
        networks:
            - backend
            - frontend


    api:
        build: ./backend
        container_name: backend
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - postgre
        networks:
            - backend
            - frontend

    front:
        build: ./front
        container_name: front
        ports:
            - 80:80
        environment:
            MONGO: mongo
        depends_on:
            - api
        networks:
            - frontend

volumes:
  postgres:
  pgadmin:

networks:
    frontend:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
    backend:
        driver: backend-driver
        ipam:
            driver: default
            config:
                - subnet: 192.168.20.0/24
# docker network create --subnet 192.168.20.0/24 backend-driver